name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
    paths-ignore: [.github/**]
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Trigger: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          
      - uses: actions/checkout@latest
      
      - name: List
        run: |
            echo "File list:"
            tree
      
